name = input("What is your name: ")
print(type(name))
surname = input("What is your surname: ")
print(type(surname))
age = int(input("What is your age: "))
print(type(age))
place = input("Where do you born: ")
print(type(place))
weight = int(input("What is your weight: "))
print(type(weight))
print(f"--{name} {surname} is {age} years old and {weight} kilograms.{name} was born in {place}.--")